### ISSUE TITLE
Is this CCZE source repository only for Debian?

### ISSUE THREAD

**Issue by vazhnov** [madhouse/ccze#3]
This repository (https://github.com/madhouse/ccze) is linked in Debian package "ccze": https://tracker.debian.org/pkg/ccze. But here is some another repositories, for example https://github.com/cornet/ccze looks more lively (but no fresh commits anyway).
If this repository is only for Debian package, please add any information about this to main page.

**Comment by algernon** [comment]
This is the upstream repository, the Debian package has this repo set as the CCZE homepage - which it kinda is. The Debian packaging is [here](https://salsa.debian.org/debian/ccze).) The other repo you linked was probably put on GitHub before I migrated the CCZE sources to git and created this repo.

(ccze was originally version controlled with [GNU Arch](https://www.gnu.org/software/gnu-arch/) (formerly TLA))
